#include "common.h"

//
// wintrust.dll proxy (PE forwarders) -- loader vector for the recflare-client-unstable build.
//
// This build's RecRoom.exe is only a stub importing RecRoom.exe.dll (the 56 MB bootstrap). That
// bootstrap -- which loads before UnityPlayer -- statically imports exactly ONE function each from
// wintrust.dll (WinVerifyTrust), bcrypt.dll and crypt32.dll, and imports NOTHING from version.dll or
// winhttp.dll. So the old version.dll vector cannot load here. wintrust is the cleanest of the three:
// it is not a KnownDLL and (unlike bcrypt/crypt32, which are pulled in during process init) is unlikely
// to be resolved from System32 before our app-dir copy is consulted. The loader searches the app dir
// first, so our wintrust.dll loads very early -- our DllMain (dllmain.c) starts the hook thread.
//
// Every one of wintrust's 165 exports is forwarded to wtrust_orig.dll (a copy of the genuine system
// wintrust.dll, deployed alongside us). Forwarders (target has a dot) mean the loader satisfies each
// call from the real DLL directly -- correct for all 165 regardless of signature, and the game only
// ever actually calls WinVerifyTrust. wtrust_orig.dll has a different basename, so there is no loop.
//
// Generated from System32\wintrust.dll (build-agnostic: these export names are stable Win32 API).
//

#pragma comment(linker, "/export:AddPersonalTrustDBPages=wtrust_orig.AddPersonalTrustDBPages")
#pragma comment(linker, "/export:CatalogCompactHashDatabase=wtrust_orig.CatalogCompactHashDatabase")
#pragma comment(linker, "/export:ComputeFirstPageHash=wtrust_orig.ComputeFirstPageHash")
#pragma comment(linker, "/export:ConfigCiFinalPolicy=wtrust_orig.ConfigCiFinalPolicy")
#pragma comment(linker, "/export:ConfigCiPackageFamilyNameCheck=wtrust_orig.ConfigCiPackageFamilyNameCheck")
#pragma comment(linker, "/export:CryptCATAdminAcquireContext=wtrust_orig.CryptCATAdminAcquireContext")
#pragma comment(linker, "/export:CryptCATAdminAcquireContext2=wtrust_orig.CryptCATAdminAcquireContext2")
#pragma comment(linker, "/export:CryptCATAdminAddCatalog=wtrust_orig.CryptCATAdminAddCatalog")
#pragma comment(linker, "/export:CryptCATAdminCalcHashFromFileHandle=wtrust_orig.CryptCATAdminCalcHashFromFileHandle")
#pragma comment(linker, "/export:CryptCATAdminCalcHashFromFileHandle2=wtrust_orig.CryptCATAdminCalcHashFromFileHandle2")
#pragma comment(linker, "/export:CryptCATAdminCalcHashFromFileHandle3=wtrust_orig.CryptCATAdminCalcHashFromFileHandle3")
#pragma comment(linker, "/export:CryptCATAdminEnumCatalogFromHash=wtrust_orig.CryptCATAdminEnumCatalogFromHash")
#pragma comment(linker, "/export:CryptCATAdminPauseServiceForBackup=wtrust_orig.CryptCATAdminPauseServiceForBackup")
#pragma comment(linker, "/export:CryptCATAdminReleaseCatalogContext=wtrust_orig.CryptCATAdminReleaseCatalogContext")
#pragma comment(linker, "/export:CryptCATAdminReleaseContext=wtrust_orig.CryptCATAdminReleaseContext")
#pragma comment(linker, "/export:CryptCATAdminRemoveCatalog=wtrust_orig.CryptCATAdminRemoveCatalog")
#pragma comment(linker, "/export:CryptCATAdminResolveCatalogPath=wtrust_orig.CryptCATAdminResolveCatalogPath")
#pragma comment(linker, "/export:CryptCATAllocSortedMemberInfo=wtrust_orig.CryptCATAllocSortedMemberInfo")
#pragma comment(linker, "/export:CryptCATCDFClose=wtrust_orig.CryptCATCDFClose")
#pragma comment(linker, "/export:CryptCATCDFEnumAttributes=wtrust_orig.CryptCATCDFEnumAttributes")
#pragma comment(linker, "/export:CryptCATCDFEnumAttributesWithCDFTag=wtrust_orig.CryptCATCDFEnumAttributesWithCDFTag")
#pragma comment(linker, "/export:CryptCATCDFEnumCatAttributes=wtrust_orig.CryptCATCDFEnumCatAttributes")
#pragma comment(linker, "/export:CryptCATCDFEnumMembers=wtrust_orig.CryptCATCDFEnumMembers")
#pragma comment(linker, "/export:CryptCATCDFEnumMembersByCDFTag=wtrust_orig.CryptCATCDFEnumMembersByCDFTag")
#pragma comment(linker, "/export:CryptCATCDFEnumMembersByCDFTagEx=wtrust_orig.CryptCATCDFEnumMembersByCDFTagEx")
#pragma comment(linker, "/export:CryptCATCDFOpen=wtrust_orig.CryptCATCDFOpen")
#pragma comment(linker, "/export:CryptCATCatalogInfoFromContext=wtrust_orig.CryptCATCatalogInfoFromContext")
#pragma comment(linker, "/export:CryptCATClose=wtrust_orig.CryptCATClose")
#pragma comment(linker, "/export:CryptCATEnumerateAttr=wtrust_orig.CryptCATEnumerateAttr")
#pragma comment(linker, "/export:CryptCATEnumerateCatAttr=wtrust_orig.CryptCATEnumerateCatAttr")
#pragma comment(linker, "/export:CryptCATEnumerateMember=wtrust_orig.CryptCATEnumerateMember")
#pragma comment(linker, "/export:CryptCATFreeSortedMemberInfo=wtrust_orig.CryptCATFreeSortedMemberInfo")
#pragma comment(linker, "/export:CryptCATGetAttrInfo=wtrust_orig.CryptCATGetAttrInfo")
#pragma comment(linker, "/export:CryptCATGetCatAttrInfo=wtrust_orig.CryptCATGetCatAttrInfo")
#pragma comment(linker, "/export:CryptCATGetMemberInfo=wtrust_orig.CryptCATGetMemberInfo")
#pragma comment(linker, "/export:CryptCATHandleFromStore=wtrust_orig.CryptCATHandleFromStore")
#pragma comment(linker, "/export:CryptCATOpen=wtrust_orig.CryptCATOpen")
#pragma comment(linker, "/export:CryptCATPersistStore=wtrust_orig.CryptCATPersistStore")
#pragma comment(linker, "/export:CryptCATPutAttrInfo=wtrust_orig.CryptCATPutAttrInfo")
#pragma comment(linker, "/export:CryptCATPutCatAttrInfo=wtrust_orig.CryptCATPutCatAttrInfo")
#pragma comment(linker, "/export:CryptCATPutMemberInfo=wtrust_orig.CryptCATPutMemberInfo")
#pragma comment(linker, "/export:CryptCATStoreFromHandle=wtrust_orig.CryptCATStoreFromHandle")
#pragma comment(linker, "/export:CryptCATVerifyMember=wtrust_orig.CryptCATVerifyMember")
#pragma comment(linker, "/export:CryptSIPCreateIndirectData=wtrust_orig.CryptSIPCreateIndirectData")
#pragma comment(linker, "/export:CryptSIPGetCaps=wtrust_orig.CryptSIPGetCaps")
#pragma comment(linker, "/export:CryptSIPGetInfo=wtrust_orig.CryptSIPGetInfo")
#pragma comment(linker, "/export:CryptSIPGetRegWorkingFlags=wtrust_orig.CryptSIPGetRegWorkingFlags")
#pragma comment(linker, "/export:CryptSIPGetSealedDigest=wtrust_orig.CryptSIPGetSealedDigest")
#pragma comment(linker, "/export:CryptSIPGetSignedDataMsg=wtrust_orig.CryptSIPGetSignedDataMsg")
#pragma comment(linker, "/export:CryptSIPPutSignedDataMsg=wtrust_orig.CryptSIPPutSignedDataMsg")
#pragma comment(linker, "/export:CryptSIPRemoveSignedDataMsg=wtrust_orig.CryptSIPRemoveSignedDataMsg")
#pragma comment(linker, "/export:CryptSIPVerifyIndirectData=wtrust_orig.CryptSIPVerifyIndirectData")
#pragma comment(linker, "/export:DllRegisterServer=wtrust_orig.DllRegisterServer")
#pragma comment(linker, "/export:DllUnregisterServer=wtrust_orig.DllUnregisterServer")
#pragma comment(linker, "/export:DriverCleanupPolicy=wtrust_orig.DriverCleanupPolicy")
#pragma comment(linker, "/export:DriverFinalPolicy=wtrust_orig.DriverFinalPolicy")
#pragma comment(linker, "/export:DriverInitializePolicy=wtrust_orig.DriverInitializePolicy")
#pragma comment(linker, "/export:FindCertsByIssuer=wtrust_orig.FindCertsByIssuer")
#pragma comment(linker, "/export:GenericChainCertificateTrust=wtrust_orig.GenericChainCertificateTrust")
#pragma comment(linker, "/export:GenericChainFinalProv=wtrust_orig.GenericChainFinalProv")
#pragma comment(linker, "/export:GetAuthenticodeSha256Hash=wtrust_orig.GetAuthenticodeSha256Hash")
#pragma comment(linker, "/export:HTTPSCertificateTrust=wtrust_orig.HTTPSCertificateTrust")
#pragma comment(linker, "/export:HTTPSFinalProv=wtrust_orig.HTTPSFinalProv")
#pragma comment(linker, "/export:IsCatalogFile=wtrust_orig.IsCatalogFile")
#pragma comment(linker, "/export:MsCatConstructHashTag=wtrust_orig.MsCatConstructHashTag")
#pragma comment(linker, "/export:MsCatFreeHashTag=wtrust_orig.MsCatFreeHashTag")
#pragma comment(linker, "/export:OfficeCleanupPolicy=wtrust_orig.OfficeCleanupPolicy")
#pragma comment(linker, "/export:OfficeInitializePolicy=wtrust_orig.OfficeInitializePolicy")
#pragma comment(linker, "/export:OpenPersonalTrustDBDialog=wtrust_orig.OpenPersonalTrustDBDialog")
#pragma comment(linker, "/export:OpenPersonalTrustDBDialogEx=wtrust_orig.OpenPersonalTrustDBDialogEx")
#pragma comment(linker, "/export:SetMessageDigestInfo=wtrust_orig.SetMessageDigestInfo")
#pragma comment(linker, "/export:SoftpubAuthenticode=wtrust_orig.SoftpubAuthenticode")
#pragma comment(linker, "/export:SoftpubCheckCert=wtrust_orig.SoftpubCheckCert")
#pragma comment(linker, "/export:SoftpubCleanup=wtrust_orig.SoftpubCleanup")
#pragma comment(linker, "/export:SoftpubDefCertInit=wtrust_orig.SoftpubDefCertInit")
#pragma comment(linker, "/export:SoftpubDllRegisterServer=wtrust_orig.SoftpubDllRegisterServer")
#pragma comment(linker, "/export:SoftpubDllUnregisterServer=wtrust_orig.SoftpubDllUnregisterServer")
#pragma comment(linker, "/export:SoftpubDumpStructure=wtrust_orig.SoftpubDumpStructure")
#pragma comment(linker, "/export:SoftpubFreeDefUsageCallData=wtrust_orig.SoftpubFreeDefUsageCallData")
#pragma comment(linker, "/export:SoftpubInitialize=wtrust_orig.SoftpubInitialize")
#pragma comment(linker, "/export:SoftpubLoadDefUsageCallData=wtrust_orig.SoftpubLoadDefUsageCallData")
#pragma comment(linker, "/export:SoftpubLoadMessage=wtrust_orig.SoftpubLoadMessage")
#pragma comment(linker, "/export:SoftpubLoadSignature=wtrust_orig.SoftpubLoadSignature")
#pragma comment(linker, "/export:SrpCheckSmartlockerEAandProcessToken=wtrust_orig.SrpCheckSmartlockerEAandProcessToken")
#pragma comment(linker, "/export:TrustDecode=wtrust_orig.TrustDecode")
#pragma comment(linker, "/export:TrustFindIssuerCertificate=wtrust_orig.TrustFindIssuerCertificate")
#pragma comment(linker, "/export:TrustFreeDecode=wtrust_orig.TrustFreeDecode")
#pragma comment(linker, "/export:TrustIsCertificateSelfSigned=wtrust_orig.TrustIsCertificateSelfSigned")
#pragma comment(linker, "/export:TrustOpenStores=wtrust_orig.TrustOpenStores")
#pragma comment(linker, "/export:WTConfigCiFreePrivateData=wtrust_orig.WTConfigCiFreePrivateData")
#pragma comment(linker, "/export:WTConvertCertCtxToChainInfo=wtrust_orig.WTConvertCertCtxToChainInfo")
#pragma comment(linker, "/export:WTGetBioSignatureInfo=wtrust_orig.WTGetBioSignatureInfo")
#pragma comment(linker, "/export:WTGetPluginSignatureInfo=wtrust_orig.WTGetPluginSignatureInfo")
#pragma comment(linker, "/export:WTGetSignatureInfo=wtrust_orig.WTGetSignatureInfo")
#pragma comment(linker, "/export:WTHelperCertCheckValidSignature=wtrust_orig.WTHelperCertCheckValidSignature")
#pragma comment(linker, "/export:WTHelperCertFindIssuerCertificate=wtrust_orig.WTHelperCertFindIssuerCertificate")
#pragma comment(linker, "/export:WTHelperCertIsSelfSigned=wtrust_orig.WTHelperCertIsSelfSigned")
#pragma comment(linker, "/export:WTHelperCheckCertUsage=wtrust_orig.WTHelperCheckCertUsage")
#pragma comment(linker, "/export:WTHelperGetAgencyInfo=wtrust_orig.WTHelperGetAgencyInfo")
#pragma comment(linker, "/export:WTHelperGetFileHandle=wtrust_orig.WTHelperGetFileHandle")
#pragma comment(linker, "/export:WTHelperGetFileHash=wtrust_orig.WTHelperGetFileHash")
#pragma comment(linker, "/export:WTHelperGetFileName=wtrust_orig.WTHelperGetFileName")
#pragma comment(linker, "/export:WTHelperGetKnownUsages=wtrust_orig.WTHelperGetKnownUsages")
#pragma comment(linker, "/export:WTHelperGetProvCertFromChain=wtrust_orig.WTHelperGetProvCertFromChain")
#pragma comment(linker, "/export:WTHelperGetProvPrivateDataFromChain=wtrust_orig.WTHelperGetProvPrivateDataFromChain")
#pragma comment(linker, "/export:WTHelperGetProvSignerFromChain=wtrust_orig.WTHelperGetProvSignerFromChain")
#pragma comment(linker, "/export:WTHelperIsChainedToMicrosoft=wtrust_orig.WTHelperIsChainedToMicrosoft")
#pragma comment(linker, "/export:WTHelperIsChainedToMicrosoftFromStateData=wtrust_orig.WTHelperIsChainedToMicrosoftFromStateData")
#pragma comment(linker, "/export:WTHelperIsInRootStore=wtrust_orig.WTHelperIsInRootStore")
#pragma comment(linker, "/export:WTHelperOpenKnownStores=wtrust_orig.WTHelperOpenKnownStores")
#pragma comment(linker, "/export:WTHelperProvDataFromStateData=wtrust_orig.WTHelperProvDataFromStateData")
#pragma comment(linker, "/export:WTIsFirstConfigCiResultPreferred=wtrust_orig.WTIsFirstConfigCiResultPreferred")
#pragma comment(linker, "/export:WTLogConfigCiScriptEvent=wtrust_orig.WTLogConfigCiScriptEvent")
#pragma comment(linker, "/export:WTLogConfigCiScriptEvent2=wtrust_orig.WTLogConfigCiScriptEvent2")
#pragma comment(linker, "/export:WTLogConfigCiSignerEvent=wtrust_orig.WTLogConfigCiSignerEvent")
#pragma comment(linker, "/export:WTLogSmartAppControlDefenderInfo=wtrust_orig.WTLogSmartAppControlDefenderInfo")
#pragma comment(linker, "/export:WTValidateBioSignaturePolicy=wtrust_orig.WTValidateBioSignaturePolicy")
#pragma comment(linker, "/export:WVTAsn1CatMemberInfo2Decode=wtrust_orig.WVTAsn1CatMemberInfo2Decode")
#pragma comment(linker, "/export:WVTAsn1CatMemberInfo2Encode=wtrust_orig.WVTAsn1CatMemberInfo2Encode")
#pragma comment(linker, "/export:WVTAsn1CatMemberInfoDecode=wtrust_orig.WVTAsn1CatMemberInfoDecode")
#pragma comment(linker, "/export:WVTAsn1CatMemberInfoEncode=wtrust_orig.WVTAsn1CatMemberInfoEncode")
#pragma comment(linker, "/export:WVTAsn1CatNameValueDecode=wtrust_orig.WVTAsn1CatNameValueDecode")
#pragma comment(linker, "/export:WVTAsn1CatNameValueEncode=wtrust_orig.WVTAsn1CatNameValueEncode")
#pragma comment(linker, "/export:WVTAsn1IntentToSealAttributeDecode=wtrust_orig.WVTAsn1IntentToSealAttributeDecode")
#pragma comment(linker, "/export:WVTAsn1IntentToSealAttributeEncode=wtrust_orig.WVTAsn1IntentToSealAttributeEncode")
#pragma comment(linker, "/export:WVTAsn1SealingSignatureAttributeDecode=wtrust_orig.WVTAsn1SealingSignatureAttributeDecode")
#pragma comment(linker, "/export:WVTAsn1SealingSignatureAttributeEncode=wtrust_orig.WVTAsn1SealingSignatureAttributeEncode")
#pragma comment(linker, "/export:WVTAsn1SealingTimestampAttributeDecode=wtrust_orig.WVTAsn1SealingTimestampAttributeDecode")
#pragma comment(linker, "/export:WVTAsn1SealingTimestampAttributeEncode=wtrust_orig.WVTAsn1SealingTimestampAttributeEncode")
#pragma comment(linker, "/export:WVTAsn1SpcFinancialCriteriaInfoDecode=wtrust_orig.WVTAsn1SpcFinancialCriteriaInfoDecode")
#pragma comment(linker, "/export:WVTAsn1SpcFinancialCriteriaInfoEncode=wtrust_orig.WVTAsn1SpcFinancialCriteriaInfoEncode")
#pragma comment(linker, "/export:WVTAsn1SpcIndirectDataContentDecode=wtrust_orig.WVTAsn1SpcIndirectDataContentDecode")
#pragma comment(linker, "/export:WVTAsn1SpcIndirectDataContentEncode=wtrust_orig.WVTAsn1SpcIndirectDataContentEncode")
#pragma comment(linker, "/export:WVTAsn1SpcLinkDecode=wtrust_orig.WVTAsn1SpcLinkDecode")
#pragma comment(linker, "/export:WVTAsn1SpcLinkEncode=wtrust_orig.WVTAsn1SpcLinkEncode")
#pragma comment(linker, "/export:WVTAsn1SpcMinimalCriteriaInfoDecode=wtrust_orig.WVTAsn1SpcMinimalCriteriaInfoDecode")
#pragma comment(linker, "/export:WVTAsn1SpcMinimalCriteriaInfoEncode=wtrust_orig.WVTAsn1SpcMinimalCriteriaInfoEncode")
#pragma comment(linker, "/export:WVTAsn1SpcPeImageDataDecode=wtrust_orig.WVTAsn1SpcPeImageDataDecode")
#pragma comment(linker, "/export:WVTAsn1SpcPeImageDataEncode=wtrust_orig.WVTAsn1SpcPeImageDataEncode")
#pragma comment(linker, "/export:WVTAsn1SpcSigInfoDecode=wtrust_orig.WVTAsn1SpcSigInfoDecode")
#pragma comment(linker, "/export:WVTAsn1SpcSigInfoEncode=wtrust_orig.WVTAsn1SpcSigInfoEncode")
#pragma comment(linker, "/export:WVTAsn1SpcSpAgencyInfoDecode=wtrust_orig.WVTAsn1SpcSpAgencyInfoDecode")
#pragma comment(linker, "/export:WVTAsn1SpcSpAgencyInfoEncode=wtrust_orig.WVTAsn1SpcSpAgencyInfoEncode")
#pragma comment(linker, "/export:WVTAsn1SpcSpOpusInfoDecode=wtrust_orig.WVTAsn1SpcSpOpusInfoDecode")
#pragma comment(linker, "/export:WVTAsn1SpcSpOpusInfoEncode=wtrust_orig.WVTAsn1SpcSpOpusInfoEncode")
#pragma comment(linker, "/export:WVTAsn1SpcStatementTypeDecode=wtrust_orig.WVTAsn1SpcStatementTypeDecode")
#pragma comment(linker, "/export:WVTAsn1SpcStatementTypeEncode=wtrust_orig.WVTAsn1SpcStatementTypeEncode")
#pragma comment(linker, "/export:WinVerifyTrust=wtrust_orig.WinVerifyTrust")
#pragma comment(linker, "/export:WinVerifyTrustEx=wtrust_orig.WinVerifyTrustEx")
#pragma comment(linker, "/export:WintrustAddActionID=wtrust_orig.WintrustAddActionID")
#pragma comment(linker, "/export:WintrustAddDefaultForUsage=wtrust_orig.WintrustAddDefaultForUsage")
#pragma comment(linker, "/export:WintrustAddProviderToProcess=wtrust_orig.WintrustAddProviderToProcess")
#pragma comment(linker, "/export:WintrustCertificateTrust=wtrust_orig.WintrustCertificateTrust")
#pragma comment(linker, "/export:WintrustGetDefaultForUsage=wtrust_orig.WintrustGetDefaultForUsage")
#pragma comment(linker, "/export:WintrustGetHash=wtrust_orig.WintrustGetHash")
#pragma comment(linker, "/export:WintrustGetRegPolicyFlags=wtrust_orig.WintrustGetRegPolicyFlags")
#pragma comment(linker, "/export:WintrustLoadFunctionPointers=wtrust_orig.WintrustLoadFunctionPointers")
#pragma comment(linker, "/export:WintrustRemoveActionID=wtrust_orig.WintrustRemoveActionID")
#pragma comment(linker, "/export:WintrustSetDefaultIncludePEPageHashes=wtrust_orig.WintrustSetDefaultIncludePEPageHashes")
#pragma comment(linker, "/export:WintrustSetRegPolicyFlags=wtrust_orig.WintrustSetRegPolicyFlags")
#pragma comment(linker, "/export:WintrustUserWriteabilityCheck=wtrust_orig.WintrustUserWriteabilityCheck")
#pragma comment(linker, "/export:mscat32DllRegisterServer=wtrust_orig.mscat32DllRegisterServer")
#pragma comment(linker, "/export:mscat32DllUnregisterServer=wtrust_orig.mscat32DllUnregisterServer")
#pragma comment(linker, "/export:mssip32DllRegisterServer=wtrust_orig.mssip32DllRegisterServer")
#pragma comment(linker, "/export:mssip32DllUnregisterServer=wtrust_orig.mssip32DllUnregisterServer")
